# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ewebshop

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f2da6dcf314f4640b36b55d7849374ce }}
        password: ${{ secrets.AzureAppService_ContainerPassword_62d58cca9c144e73a861ddaa877325df }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f2da6dcf314f4640b36b55d7849374ce }}/webshop:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ewebshop'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e14c20f56c234e69ad459749cacbb546 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f2da6dcf314f4640b36b55d7849374ce }}/webshop:${{ github.sha }}'